const errorCode = {
    SECURITY_HASH_OR_USER_ID_MISMATCH_ERROR: "SECURITY_HASH_OR_USER_ID_MISMATCH_ERROR",
    SURVEY_ALREADY_ANSWERED_ERROR: "SURVEY_ALREADY_ANSWERED_ERROR"
}

module.exports = errorCode